"""
state.py
--------
Defines the LangGraph GraphState TypedDict.
This is the single shared data object that flows between all nodes in the graph.
Every node reads from and writes to this state object.
"""

from typing import TypedDict, List, Optional
from langchain_core.documents import Document


class GraphState(TypedDict):
    """
    The complete state object for the RAG LangGraph workflow.

    Fields:
        query           : Original user question (string).
        retrieved_docs  : Raw Document objects returned by ChromaDB retrieval.
        chunks_text     : Extracted text from retrieved docs (for LLM prompt).
        sources         : Human-readable source citations (e.g. "kb.pdf, page 3").
        similarity_scores: Raw similarity scores from ChromaDB for each chunk.
        confidence      : Computed confidence scalar in [0.0, 1.0].
        has_context     : True if at least one chunk was retrieved above threshold.
        llm_answer      : Raw answer generated by the LLM (may be None on error).
        final_answer    : The answer that will be shown to the user
                          (= llm_answer, or human-edited answer after HITL).
        escalated       : True if the query was escalated to a human agent.
        error           : Error message string if any node failed; None otherwise.
    """

    query: str
    retrieved_docs: List[Document]
    chunks_text: List[str]
    sources: List[str]
    similarity_scores: List[float]
    confidence: float
    has_context: bool
    llm_answer: Optional[str]
    final_answer: Optional[str]
    escalated: bool
    error: Optional[str]
